<a href="https://colab.research.google.com/github/arushiagarwal892-rgb/gitcode/blob/main/nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("/content/drive/MyDrive/mlcsvfiles/SMS Spam Dataset.csv")

In [5]:
df.columns

Index(['sms', 'label'], dtype='object')

In [13]:
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [21]:
def clean_text(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z\s]','',text)
  text=re.sub(r'https\S+','',text)
  words=word_tokenize(text)
  stop_words=set(stopwords.words('english'))
  filtered_words=[word for word in words if word not in stop_words]
  stemmer=PorterStemmer()
  words=[stemmer.stem(word) for word in filtered_words]
  # words=' '.join(words
  return words
text1='Hello how are you. i am fineing loving'
clean_text(text1)

['hello', 'fine', 'love']

In [22]:
df['clean_text']=df['sms'].apply(lambda x:clean_text(x))

In [23]:
df['label'].value_counts()

label
0    4827
1     747
Name: count, dtype: int64

In [25]:
from imblearn.over_sampling import RandomOverSampler
X=df.drop('label',axis=1)
y=df['label']

In [31]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5569    1
5570    0
5571    0
5572    0
5573    0
Name: label, Length: 5574, dtype: int64

In [28]:
ros=RandomOverSampler()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
y_train

0       1
1       0
2       0
3       0
4       0
       ..
7741    1
7742    1
7743    1
7744    1
7745    1
Name: label, Length: 7746, dtype: int64

In [29]:
X_train,y_train=ros.fit_resample(X_train,y_train)